version: '3'

services:
  server:
    build: server/
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    build: database/
    volumes:
      - "./database/sampledata/:/var/lib/postgresql/newdata/pgdata/"